server:
  port: 8085
spring:  application:    name: KafkaProducer
      datasource:    url: jdbc:mysql://192.168.1.164:3306/kings
    username: kings
    password: kings@123
  jpa:    show-sql: true    hibernate:      naming:        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy 
    properties:
      hibernate :
          dialect : org.hibernate.dialect.MySQL5InnoDBDialect 